export const selectors = {
    userInput: '#user',
    passwordInput: '#password',
    buttonSubmint: 'button[type="submit"][data-testid="submitButton"]',
    messageErrorAlertLogin: '.message',
    messageErrorInvalidFieldLogin: '.errorMessage',
    messageErrorClass: '.errorMessage',
    name: "#name",
    lastName: '#lastName',
    dayOfBirth: '#dayOfBirth',
    monthOfBirth: '#monthOfBirth',
    yearOfBirth: '#yearOfBirth',
    cpf: '#cpf',
    homePhone: '#homePhone',
    zipCode: '#zipCode',
    streetType: '#streetType',
    streetName: '#streetName',
    streetNumber: '#streetNumber',
    neighborhood: '#neighborhood',
    state: '#state',
    city: '#city',
    email: '#email',
    emailNewsletter: '#emailNewsletter',
    privacy: '#privacy',
    buttonRegister: '[qa-auto="gift-wrapping-select-button"]',
    validateLoginSussefull: '.user__content'
   
}